# This is a basic workflow to help you get started with Actions

name: DalamudPluginPR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request
      uses: daemitus/DalamudPluginPR2@master
      with:
        # ===== Required inputs =====
        # Personal access token to authenticate with GitHub.
        # Your access token should be stored in a repository secret
        token: ${{ secrets.PAT }}

        # The name of your plugin, used in determining the manifest path.
        plugin_name: DailyDuty

        # ===== Optional inputs =====
        # Enable or disable the entire dalamud_plugin_pr2.
        # This can be true/false or a partial string searched for within the commit message.
        # Default: "[PR]"
        enabled: "[PR]"

        # If the artifact should be commited to testing instead of plugins.
        # This can be true/false or a partial string searched for within the commit message.
        # Default: "[TEST]"
        testing: "[Testing]"

        # Repository where your artifact will be committed.
        # Default: ${{ github.repository_owner }}/DalamudPluginsD17
        repository: ${{ github.repository_owner }}/DalamudPluginsD17

        # Repository where the PR will be created.
        # Default: goatcorp/DalamudPluginsD17
        pr_repository: goatcorp/DalamudPluginsD17
